### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by lennardv2** [lennardv2/ehh#1]
https://user-images.githubusercontent.com/168357/104209678-5076e800-5432-11eb-9e13-55cd48c6fa7b.mp4

**Comment by lvoogdt** [comment]
![Kapture 2021-01-11 at 17 26 36](https://user-images.githubusercontent.com/168357/104209913-8d42df00-5432-11eb-9ab2-8ca210fd2404.gif)

**Comment by lvoogdt** [comment]
![Kapture 2021-01-11 at 18 34 22](https://user-images.githubusercontent.com/168357/104217475-b87dfc00-543b-11eb-8936-d585c7db6114.gif)

**Comment by lennardv2** [comment]
https://user-images.githubusercontent.com/168357/185811288-a5767eb8-3da9-46eb-a9a7-5b45fab97513.mp4

**Comment by lennardv2** [comment]
https://user-images.githubusercontent.com/168357/185811458-d383212a-dc37-4f46-9abe-bcf708509496.mp4

**Comment by lennardv2** [comment]
![hey-commands](https://user-images.githubusercontent.com/168357/224775008-cd52176b-bfa2-4e0c-a66b-f3e920eba38f.gif)

**Comment by lennardv2** [comment]
https://github.com/lennardv2/ehh/assets/168357/8ec1767c-437b-4991-9ca8-ca7828579412
